#!/bin/bash
OPTIONS="Create Status Delete Quit"
select opt in $OPTIONS; do
  case $opt in
    "Create")
      echo "Enter number of web instances NGINX:"
      read WEB
      echo "Enter number of db instances in Galera cluster:"
      read DB
      echo "Enter number of control container:"
      read CON
      echo "Use default parameters (y/n)"
      read DEF
      echo "Next containers will be created: web - $WEB, MariaDB - $DB, control - $CON."
      echo "Confirm or discard (y/n):"
      read CONFIRM
      if [ "$CONFIRM" = "y" ]; then
        echo Created!
      else
        echo Discarded!
      fi
    ;;
    "Status")
      docker ps -a
    ;;
    "Delete")
      echo "Delete"
    ;;
    "Apply")
      echo "Apply"
    ;;
    "Quit")
      break
    ;;
    *) echo invalid option;;
  esac
done

